### ISSUE TITLE
Larger examples

### ISSUE THREAD

**Issue by heinrich5991** [Gbps/plugshark#1]
Is there a larger wireshark dissector written using this crate? I can see the `simple-example/` in the root but that's just a toy protocol.

**Comment by Gbps** [comment]
Hey there,

Thanks for the interest in the project! I have uploaded my project I am working on in my spare time using this framework: https://github.com/Gbps/elpis-parser

**Comment by Gbps** [comment]
Closing this for now, please feel free to comment again on this for further questions.
